---
title: "RLSeq Report"
output: 
  html_document:
    code_folding: hide
    theme: flatly
    highlight: textmate
params:
  object: "placeholder"
---


```{r setup, include=FALSE, echo=FALSE}
list2env(params, envir = environment())

# Libraries
library(magrittr)
library(rlang)

# Wrangle results and trigger conditional templates
rlres <- object@metadata$results
rlreslst <- lapply(slotNames(rlres), function(sn) {
  tryCatch(rlresult(object, sn), error = function(e) {NULL})
})
names(rlreslst) <- slotNames(rlres)
isnull <- sapply(rlreslst, is.null)

```

<br>

Sample name: <strong>`r sampleName`</strong>

Sample type: <strong>`r paste0(mode, "-Seq")`</strong>

Genome: <strong>`r genome`</strong>

Time finished: <strong>`r date()`</strong>


## Quality Report

<hr>

```{r annoShow, child=system.file("Rmd", "correlation_template.Rmd", package = "RLSeq"), eval=isnull["correlationMat"]}
```

```{r annoShow, child=system.file("Rmd", "RLFS_template.Rmd", package = "RLSeq"), eval=isnull["rlfsRes"]}
```

```{r annoShow, child=system.file("Rmd", "RLFS_template.Rmd", package = "RSeqR"), eval=isnull["rlfsRes"]}
```

```{r annoShow, child=system.file("Rmd", "RLFS_template.Rmd", package = "RSeqR"), eval=is.list(featureTest)}
```

```{r annoShow, child=system.file("Rmd", "annotation_template.Rmd", package = "RSeqR"), eval=is.list(RLoopRegions)}
```



### Peak calling

```{r totalPeaks}
# TODO: What should this number be? Can we arrive at a more robust estimate?
total_peaks_color <- ifelse(total_peaks < 3000, 'red', ifelse(total_peaks < 6000, 'orange', 'green'))
```

The peak caller `macs` was used for peak calling. Number of peaks called: <strong style="color: `r total_peaks_color`">`r total_peaks`</strong>

***

&nbsp;
<hr />
<p style="text-align: center;">RSeq © 2021, <a href="https://gccri.bishop-lab.uthscsa.edu/"  target="_blank">Bishop Lab</a>, UT Health San Antonio</p>
<p style="text-align: center;">RSeq maintainer: <span style="color: #808080;"><em>millerh1@uthscsa.edu</em></span></p>

&nbsp;
