#' GRanges. Peaks from running RSeq-CLI on SRX1025890 - in "hg38" format.
"SRX1025890_peaks"

#' GRanges. Peaks from running liftUtil(SRX1035890_peaks, "hg38", "hg19") in "hg19" format.
"SRX1025890_peaks_hg19"

#' data.frame. Contains information about the genes available in UCSC database.
#' Result of running RSeqR:::buildAvailableGenomes()
"available_genomes"

#' List of GRanges. Contains genomic masks for several commons species.
#' See data-raw/masked_genomes.R for details.
"genomeMasks"

#' List of list of tibbles. Containing genomic annotations for use with RSeqR.
#' See data-raw/anotationLst.R for details.
"annotationLst"

#' A Caret model used for preprocessing datasets in predictCondition().
"prepFeatures"

#' A Caret model used for predicting whether a peakset resembles 
#' "case" (normal) or "control" (RNaseH1-like) conditions. 
#' Used in predictionCondition().
"fftModel"

#' The matrix generated by summarizing all hg38 RMapDB bigWig files around the 
#' "Gold-Standard" R-loop sites defined by Chedin et al. https://doi.org/10.15252/embj.2020106394
#' Columns are sample names and rows are hg38 genomic coordinates. 
#' See data-raw/gsSignalRMapDB.R for processing steps.
"gsSignalRMapDB"

#' A Tibble containing the R-loop regions identified through metanalysis of publicly-available
#' R-loop mapping samples (as described in Miller et al. 2021). The tibble includes additional
#' information, such as the RLoop Region ID, the number of studies, samples, and modes
#' that RL Region is found in, the average signal and qVal of peaks overlapping with it, 
#' any genes which overlap with it, the correlation with expression corrR and corrPval,
#' and whether the RLoop exists in Repeat regions or RLFS regions.
"rlRegions"
