on: push
jobs:
  install-and-test:
    name: Install and Test
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.4' # The R version to download (if necessary) and use.
    - shell: Rscript {0}
      name: Installation
      run: |
        install.packages("devtools")
        devtools::install_dev_deps()
        devoolts::install_cran("co")
    - shell: Rscript {0}
      name: Testing
      run: |
        devtools::test()
    - shell: Rscript {0}
      name: Code coverage
      run: |
        covr::package_coverage(path = ".")
